### ISSUE TITLE
Fatal: could not read Password for 'https://***@github.com': No such device or address

### ISSUE THREAD

**Issue by yuxiang660** [enriikke/gatsby-gh-pages-action#12]
I failed to use "gatsby-gh-pages-action" to publish my "Gatsby" static web sites to "gh-pages" branch with following error at last step:
<img width="516" alt="error" src="https://user-images.githubusercontent.com/6477589/72037542-92c69000-32d9-11ea-881a-44e8cba00af1.png">

Could you help to fix it?

Here is my `yml` file:

```yml
name: Gatsby Publish

on: [push]

jobs:
  buil1d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
```

- I have set my `GITHUB_TOKEN` (with the same name) per the [doc](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).

- I can use `npm run deploy` command on my local repository (I have set "gh-pages" dependency in my project with correct `pathPrefix`) to publish local static web sites to "gh-pages" branch.

Thx.
