### ISSUE TITLE
Arguments are not forwarded when using NPM

### ISSUE THREAD

**Issue by MatthijsMud** [enriikke/gatsby-gh-pages-action#13]
While using this action to create a test build on a `gh-pages` branch using Gatsby's default starter, I ran into an issue where the site was not generated correctly; none of the links included the path prefix. This is apparently because the arguments are not forward to the NPM build command, so Gatsby did not know that it should prefix any paths.

NPM requires an extra set of dashes to forward any parameters to a given command, according to [this StackOverflow answer](https://stackoverflow.com/a/3042512). So depending on the package manager, the build command should look something like the following.
```shell
$ yarn run build --prefix-paths
$ npm run build -- --prefix-paths
```

**Comment by enriikke** [comment]
Hi @MatthijsMud! Thanks for opening an issue. I believe you can still pass the extra set of dashes as part of the `gatsby-args` input. For example:

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: -- --prefix-paths
```

I think it's still a great idea to highlight this in the documentation. I'll be happy to accept a PR for that if you have some time. Otherwise I can try to update it sometime this week.

Would you mind first confirming that works for you? 😃
