### ISSUE TITLE
Support secrets.GITHUB_TOKEN

### ISSUE THREAD

**Issue by TMiguelT** [enriikke/gatsby-gh-pages-action#27]
If you are deploying to a `gh-pages` branch of the current repo, you should be able to use `secrets.GITHUB_TOKEN` instead of needing a deploy key at all. This would then work the same as all the other github-pages deployment actions, e.g. https://github.com/peaceiris/actions-gh-pages#github-actions-for-github-pages.

This would massively reduce the setup time for using this, since `GITHUB_TOKEN` exists by default, whereas creating an access token is a bit of a pain.

**Comment by oscarmorrison** [comment]
Yes. Something like ` github-token: ${{ secrets.GITHUB_TOKEN }}` would be excellent

**Comment by maiwald** [comment]
I have switched to [peaceiris/actions-gh-pages](https://github.com/marketplace/actions/github-pages-action). It is not as flexible as `gatsby-gh-pages-action` but supports `GITHUB_TOKEN`. Their README has [instructions for deploying Gatsby sites](https://github.com/marketplace/actions/github-pages-action#%EF%B8%8F-gatsby).

**Comment by sergiomcalzada** [comment]
You can do it just with

```
name: Gatsby Publish

on:
  push:
    branches:
      - gatsby

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: x-access-token:${{ secrets.GITHUB_TOKEN }}
          deploy-branch: main
```
