### ISSUE TITLE
gatsby build "" error

### ISSUE THREAD

**Issue by douglashellowell** [enriikke/gatsby-gh-pages-action#51]
I'm not sure if i've missed something (fairly new to GH actions) but it _looks_ like the default `gatsby-args :""` is being passed as a flag and messing it up?

`main.yml`

```yml
name: Gatsby Delopy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
```

`github actions output`
```
[...]
Finished installing dependencies.
Ready to build your Gatsby site!
Building with: npm run build 
npm run build 

> gatsby-starter-blog@0.1.0 build /home/runner/work/douglashellowell.github.io/douglashellowell.github.io
> gatsby build ""

error gatsby build
[...]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-starter-blog@0.1.0 build: `gatsby build ""`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gatsby-starter-blog@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-11-21T13_36_59_181Z-debug.log
Error: The process 'npm' failed with exit code 1
```

---

Altering the `main.yml` to include a flag - e.g`gatsby-args: --verbose` fixed it

```yml
[...]
      - name: Gatsby Publish
        uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          gatsby-args: --verbose

```
