### ISSUE TITLE
deploy-repo "Knobs & Handles" valid inputs?

### ISSUE THREAD

**Issue by itsrobli** [enriikke/gatsby-gh-pages-action#52]
Hi there

Anybody know what constitutes a valid input for the key `deploy-repo`?

I have tried `<username>/<repo>`,  `<repo>`, and `http://.....git`

This is the build log message I get:

> Warning: Unexpected input(s) 'deploy-repo', valid inputs are ['access-token', 'deploy-branch', 'gatsby-args']

This is my yml file

```yml
name: Gatsby Publish

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
          deploy-repo: <see above>
          gatsby-args: --prefix-paths
```
