### ISSUE TITLE
Can i use env from github action config?

### ISSUE THREAD

**Issue by xxidbr9** [enriikke/gatsby-gh-pages-action#67]
i was try use github env key, but doesn't have any affect with my gatsby app

this is my config

```yaml
name: Publish Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  GATSBY_ENV: "github"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths

```
