### ISSUE TITLE
Additional environmental variables

### ISSUE THREAD

**Issue by ajmeese7** [enriikke/gatsby-gh-pages-action#72]
With my Gatsby CI I am using Contentful, which requires the additional secret variables of `CONTENTFUL_ACCESS_TOKEN` and `CONTENTFUL_SPACE_ID`. If you could add the option to pass additional custom user variables to this action that would be awesome!

I am passing the following as my action configuration:

```yml
- uses: enriikke/gatsby-gh-pages-action@v2
  with:
    access-token: ${{ secrets.GH_ACCESS_TOKEN }}
    deploy-branch: gh-pages
    gatsby-args: --prefix-paths
  env:
    CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
    CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
```

But the `env` parameter's values are not respected when yarn is building my project.
