### ISSUE TITLE
Node 12 is deprecated

### ISSUE THREAD

**Issue by hrenaud** [enriikke/gatsby-gh-pages-action#76]
Upgrade to 14.5 minimum for Gatsby.

Regards

**Comment by markconroy** [comment]
Gatsby V5 needs Node 18. Any chance we could have support for that?

**Comment by Zenulous** [comment]
Just add a step in your workflow to install a necessary Node.js version on a default runner, like
```
      - uses: actions/setup-node@v3
        with:
          node-version: 18
```

**Comment by hrenaud** [comment]
This is a good solution. You should update the readme.md to explain it and specify where to place it in the yml.

**Comment by markconroy** [comment]
Hi @Zenulous 

Thanks for that tip. I didn't realise we could do that. For any one reading, here's how to use it:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: gh-pages
```
